//
// LESS - Leaner CSS v1.4.0
// http://lesscss.org
//
// Copyright (c) 2009-2013, Alexis Sellier
// Licensed under the Apache 2.0 License.
//

(function(x,ca){function n(a){return x.less[a.split("/")[1]]}function ja(){for(var a=document.getElementsByTagName("style"),b=0;b<a.length;b++)if(a[b].type.match(ka)){var c=new j.tree.parseEnv(j);c.filename=document.location.href.replace(/#.*$/,"");(new j.Parser(c)).parse(a[b].innerHTML||"",function(c,f){if(c)return Z(c,"inline");var e=f.toCSS(j),l=a[b];l.type="text/css";l.styleSheet?l.styleSheet.cssText=e:l.innerHTML=e})}}function la(a,b){for(var c=0;c<j.sheets.length;c++)ma(j.sheets[c],a,b,j.sheets.length-
(c+1))}function $(a,b){var c=/^((?:[a-z-]+:)?\/\/(?:[^\/\?#]*\/)|([\/\\]))?((?:[^\/\\\?#]*[\/\\])*)([^\/\\\?#]*)([#\?].*)?$/,d=a.match(c),f={},e=[];if(!d)throw Error("Could not parse sheet href - '"+a+"'");if(!d[1]||d[2]){c=b.match(c);if(!c)throw Error("Could not parse page url - '"+b+"'");d[1]=c[1];d[2]||(d[3]=c[3]+d[3])}if(d[3]){e=d[3].replace("\\","/").split("/");for(c=0;c<e.length;c++)".."===e[c]&&0<c&&(e.splice(c-1,2),c-=2)}f.hostPart=d[1];f.directories=e;f.path=d[1]+e.join("/");f.fileUrl=f.path+
(d[4]||"");f.url=f.fileUrl+(d[5]||"");return f}function ma(a,b,c,d){var f=$(a.href,x.location.href),e=f.url,l=w&&w.getItem(e),h=w&&w.getItem(e+":timestamp"),z={css:l,timestamp:h},k;a instanceof j.tree.parseEnv?k=new j.tree.parseEnv(a):(k=new j.tree.parseEnv(j),k.entryPath=f.path,k.mime=a.type);if(k.relativeUrls)if(j.rootpath){var l=k,h=j.rootpath,g;var n=k.entryPath;g=$(f.path);var p=$(n),m,s="";if(g.hostPart!==p.hostPart)g="";else{m=Math.max(p.directories.length,g.directories.length);for(n=0;n<m&&
p.directories[n]===g.directories[n];n++);p=p.directories.slice(n);g=g.directories.slice(n);for(n=0;n<p.length-1;n++)s+="../";for(n=0;n<g.length-1;n++)s+=g[n]+"/";g=s}l.rootpath=$(h+g).path}else k.rootpath=f.path;else j.rootpath||(k.rootpath=k.entryPath);var l=a.type,t=function(h,l){da+=h.replace(/@import .+?;/ig,"");if(!c&&z&&l&&(new Date(l)).valueOf()===(new Date(z.timestamp)).valueOf())R(z.css,a),b(null,null,h,a,{local:!0,remaining:d},e);else try{k.contents[e]=h,k.paths=[f.path],k.filename=e,k.rootFilename=
k.rootFilename||e,(new j.Parser(k)).parse(h,function(c,oa){if(c)return b(c,null,null,a);try{if(b(c,oa,h,a,{local:!1,lastModified:l,remaining:d},e),k.rootFilename===e){var f=document.getElementById("less-error-message:"+ea(e));f&&f.parentNode.removeChild(f)}}catch(pa){b(pa,null,null,a)}})}catch(m){b(m,null,null,a)}},q=function(c,d){b({type:"File",message:"'"+d+"' wasn't found ("+c+")"},null,null,a)},r=function(a,b,c){200<=a.status&&300>a.status?b(a.responseText,a.getResponseHeader("Last-Modified")):
"function"===typeof c&&c(a.status,e)},v=qa(),h=aa?j.fileAsync:j.async;"function"===typeof v.overrideMimeType&&v.overrideMimeType("text/css");v.open("GET",e,h);v.setRequestHeader("Accept",l||"text/x-less, text/css; q=0.9, */*; q=0.5");v.send(null);aa&&!j.fileAsync?0===v.status||200<=v.status&&300>v.status?t(v.responseText):q(v.status,e):h?v.onreadystatechange=function(){4==v.readyState&&r(v,t,q)}:r(v,t,q)}function ea(a){return a.replace(/^[a-z]+:\/\/?[^\/]+/,"").replace(/^\//,"").replace(/\.[a-zA-Z]+$/,
"").replace(/[^\.\w-]+/g,"-").replace(/\./g,":")}function R(a,b,c){var d,f=b.href||"",e="less:"+(b.title||ea(f));if(null===(d=document.getElementById(e)))d=document.createElement("style"),d.type="text/css",b.media&&(d.media=b.media),d.id=e,b=b&&b.nextSibling||null,(b||document.getElementsByTagName("head")[0]).parentNode.insertBefore(d,b);if(d.styleSheet)try{d.styleSheet.cssText=a}catch(l){throw Error("Couldn't reassign styleSheet.cssText.");}else b=document.createTextNode(a),0<d.childNodes.length?
d.firstChild.nodeValue!==b.nodeValue&&d.replaceChild(b,d.firstChild):d.appendChild(b);if(c&&w){I("saving "+f+" to cache.");try{w.setItem(f,a),w.setItem(f+":timestamp",c)}catch(h){I("failed to save")}}}function qa(){if(x.XMLHttpRequest)return new XMLHttpRequest;try{return new ActiveXObject("MSXML2.XMLHTTP.3.0")}catch(a){return I("browser doesn't support AJAX."),null}}function I(a){"development"==j.env&&"undefined"!==typeof console&&console.log("less: "+a)}function Z(a,b){var c="less-error-message:"+
ea(b||""),d=document.createElement("div"),f,e,l=[];e=a.filename||b;var h=e.match(/([^\/]+(\?.*)?)$/)[1];d.id=c;d.className="less-error-message";e="<h3>"+(a.type||"Syntax")+"Error: "+(a.message||"There is an error in your .less file")+'</h3><p>in <a href="'+e+'">'+h+"</a> ";h=function(a,b,c){a.extract[b]!=ca&&l.push('<li><label>{line}</label><pre class="{class}">{content}</pre></li>'.replace(/\{line\}/,(parseInt(a.line)||0)+(b-1)).replace(/\{class\}/,c).replace(/\{content\}/,a.extract[b]))};a.extract?
(h(a,0,""),h(a,1,"line"),h(a,2,""),e+="on line "+a.line+", column "+(a.column+1)+":</p><ul>"+l.join("")+"</ul>"):a.stack&&(e+="<br/>"+a.stack.split("\n").slice(1).join("<br/>"));d.innerHTML=e;R(".less-error-message ul, .less-error-message li {\nlist-style-type: none;\nmargin-right: 15px;\npadding: 4px 0;\nmargin: 0;\n}\n.less-error-message label {\nfont-size: 12px;\nmargin-right: 15px;\npadding: 4px 0;\ncolor: #cc7777;\n}\n.less-error-message pre {\ncolor: #dd6666;\npadding: 4px 0;\nmargin: 0;\ndisplay: inline-block;\n}\n.less-error-message pre.line {\ncolor: #ff0000;\n}\n.less-error-message h3 {\nfont-size: 20px;\nfont-weight: bold;\npadding: 15px 0 5px 0;\nmargin: 0;\n}\n.less-error-message a {\ncolor: #10a\n}\n.less-error-message .error {\ncolor: red;\nfont-weight: bold;\npadding-bottom: 2px;\nborder-bottom: 1px dashed red;\n}",
{title:"error-message"});d.style.cssText="font-family: Arial, sans-serif;border: 1px solid #e00;background-color: #eee;border-radius: 5px;-webkit-border-radius: 5px;-moz-border-radius: 5px;color: #e00;padding: 15px;margin-bottom: 15px";"development"==j.env&&(f=setInterval(function(){document.body&&(document.getElementById(c)?document.body.replaceChild(d,document.getElementById(c)):document.body.insertBefore(d,document.body.firstChild),clearInterval(f))},10))}Array.isArray||(Array.isArray=function(a){return"[object Array]"===
Object.prototype.toString.call(a)||a instanceof Array});Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=this.length>>>0,d=0;d<c;d++)d in this&&a.call(b,this[d],d,this)});Array.prototype.map||(Array.prototype.map=function(a,b){for(var c=this.length>>>0,d=Array(c),f=0;f<c;f++)f in this&&(d[f]=a.call(b,this[f],f,this));return d});Array.prototype.filter||(Array.prototype.filter=function(a,b){for(var c=[],d=0;d<this.length;d++)a.call(b,this[d])&&c.push(this[d]);return c});Array.prototype.reduce||
(Array.prototype.reduce=function(a){var b=this.length>>>0,c=0;if(0===b&&1===arguments.length)throw new TypeError;if(2<=arguments.length)var d=arguments[1];else{do{if(c in this){d=this[c++];break}if(++c>=b)throw new TypeError;}while(1)}for(;c<b;c++)c in this&&(d=a.call(null,d,this[c],c,this));return d});Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length,d=b||0;if(!c||d>=c)return-1;for(0>d&&(d+=c);d<c;d++)if(Object.prototype.hasOwnProperty.call(this,d)&&a===this[d])return d;
return-1});Object.keys||(Object.keys=function(a){var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b});String.prototype.trim||(String.prototype.trim=function(){return String(this).replace(/^\s\s*/,"").replace(/\s\s*$/,"")});var j,k;"object"===typeof environment&&"[object Environment]"==={}.toString.call(environment)?(j="undefined"===typeof x?{}:x.less={},k=j.tree={},j.mode="rhino"):"undefined"===typeof x?(j=exports,k=n("./tree"),j.mode="node"):("undefined"===typeof x.less&&
(x.less={}),j=x.less,k=x.less.tree={},j.mode="browser");j.Parser=function(a){function b(){r=v[q];y=u=m}function c(){v[q]=r;y=m=u}function d(){m>y&&(v[q]=v[q].slice(m-y),y=m)}function f(a){a=a.charCodeAt(0);return 32===a||10===a||9===a}function e(a){var b;if(a instanceof Function)return a.call(C.parsers);if("string"===typeof a)a=p.charAt(m)===a?a:null,b=1,d();else if(d(),a=a.exec(v[q]))b=a[0].length;else return null;if(a){for(var c=m+v[q].length,e=m+=b;m<c&&f(p.charAt(m));)m++;v[q]=v[q].slice(b+(m-
e));y=m;0===v[q].length&&q<v.length-1&&q++;return"string"===typeof a?a:1===a.length?a[0]:a}}function l(a,b){var c=e(a);if(c)return c;h(b||("string"===typeof a?"expected '"+a+"' got '"+p.charAt(m)+"'":"unexpected token"))}function h(a,b){var c=Error(a);c.index=m;c.type=b||"Syntax";throw c;}function z(a){return"string"===typeof a?p.charAt(m)===a:a.test(v[q])?!0:!1}function g(a,b){for(var c=a,d=-1;0<=c&&"\n"!==b.charAt(c);c--)d++;return{line:"number"===typeof a?(b.slice(0,a).match(/\n/g)||"").length:
null,column:d}}function s(a,b,c){a=g(a,b).line+1;c="browser"===j.mode||"rhino"===j.mode?c.filename:n("path").resolve(c.filename);return{lineNumber:a,fileName:c}}function t(a,b){var c;c=a.filename&&b.filename&&a.filename!==b.filename?C.imports.contents[a.filename]:p;var d=g(a.index,c),e=d.line,d=d.column,f=c.split("\n");this.type=a.type||"Syntax";this.message=a.message;this.filename=a.filename||b.filename;this.index=a.index;this.line="number"===typeof e?e+1:null;this.callLine=a.call&&g(a.call,c).line+
1;this.callExtract=f[g(a.call,c).line];this.stack=a.stack;this.column=d;this.extract=[f[e-1],f[e],f[e+1]]}var p,m,q,r,u,x,v,y,C;a instanceof k.parseEnv||(a=new k.parseEnv(a));var D=function(){},w=this.imports={paths:a.paths||[],queue:[],files:a.files,contents:a.contents,mime:a.mime,error:null,push:function(b,c){var d=this;this.queue.push(b);j.Parser.importer(b,this.paths,function(a,e,f){d.queue.splice(d.queue.indexOf(b),1);var h=f in d.files;d.files[f]=e;a&&!d.error&&(d.error=a);c(a,e,h);0===d.queue.length&&
D(d.error)},a)}};this.env=a=a||{};this.optimization="optimization"in this.env?this.env.optimization:1;this.env.filename=this.env.filename||null;return C={imports:w,parse:function(b,c){var d,f,h,l=null;m=q=y=x=0;p=b.replace(/\r\n/g,"\n");p=p.replace(/^\uFEFF/,"");f=[[]];h=0;for(var z=/(?:@\{[\w-]+\}|[^"'`\{\}\/\(\)\\])+/g,g=/\/\*(?:[^*]|\*+[^\/*])*\*+\/|\/\/.*/g,s=/"((?:[^"\\\r\n]|\\.)*)"|'((?:[^'\\\r\n]|\\.)*)'|`((?:[^`]|\\.)*)`/g,H=0,r,A=f[0],u,B=0,w,E;B<p.length;){z.lastIndex=B;if((r=z.exec(p))&&
r.index===B)B+=r[0].length,A.push(r[0]);w=p.charAt(B);g.lastIndex=s.lastIndex=B;if((r=s.exec(p))&&r.index===B)B+=r[0].length,A.push(r[0]);else{if(!u&&"/"===w&&(E=p.charAt(B+1),"/"===E||"*"===E))if((r=g.exec(p))&&r.index===B){B+=r[0].length;A.push(r[0]);continue}switch(w){case "{":if(!u){H++;A.push(w);break}case "}":if(!u){H--;A.push(w);f[++h]=A=[];break}case "(":if(!u){u=!0;A.push(w);break}case ")":if(u){u=!1;A.push(w);break}default:A.push(w)}B++}}0!=H&&(l=new t({index:B-1,type:"Parse",message:0<
H?"missing closing `}`":"missing opening `{`",filename:a.filename},a));v=f.map(function(a){return a.join("")});if(l)return c(new t(l,a));try{d=new k.Ruleset([],e(this.parsers.primary)),d.root=!0}catch(F){return c(new t(F,a))}var G=d.eval;d.toCSS=function(b,c){b=b||{};var d=new k.evalEnv(b);"object"===typeof c&&!Array.isArray(c)&&(c=Object.keys(c).map(function(a){var b=c[a];b instanceof k.Value||(b instanceof k.Expression||(b=new k.Expression([b])),b=new k.Value([b]));return new k.Rule("@"+a,b,!1,
0)}),d.frames=[new k.Ruleset(null,c)]);try{var e=G.call(this,d).toCSS([],{compress:b.compress||!1,dumpLineNumbers:a.dumpLineNumbers,strictUnits:!1===b.strictUnits?!1:!0})}catch(f){throw new t(f,a);}return b.yuicompress&&"node"===j.mode?n("ycssmin").cssmin(e):b.compress?e.replace(/(\s)+/g,"$1"):e};if(m<p.length-1){m=x;h=p.split("\n");f=(p.slice(0,m).match(/\n/g)||"").length+1;z=m;for(g=-1;0<=z&&"\n"!==p.charAt(z);z--)g++;l={type:"Parse",message:"Unrecognised input",index:m,filename:a.filename,line:f,
column:g,extract:[h[f-2],h[f-1],h[f]]}}D=function(b){(b=l||b||C.imports.error)?(b instanceof t||(b=new t(b,a)),c(b)):c(null,d)};0===this.imports.queue.length&&D()},parsers:{primary:function(){for(var a,b=[];(a=e(this.extendRule)||e(this.mixin.definition)||e(this.rule)||e(this.ruleset)||e(this.mixin.call)||e(this.comment)||e(this.directive))||e(/^[\s\n]+/)||e(/^;+/);)a&&b.push(a);return b},comment:function(){var a;if("/"===p.charAt(m)){if("/"===p.charAt(m+1))return new k.Comment(e(/^\/\/.*/),!0);if(a=
e(/^\/\*(?:[^*]|\*+[^\/*])*\*+\/\n?/))return new k.Comment(a)}},entities:{quoted:function(){var a;a=m;var b;"~"===p.charAt(a)&&(a++,b=!0);if(!('"'!==p.charAt(a)&&"'"!==p.charAt(a))&&(b&&e("~"),a=e(/^"((?:[^"\\\r\n]|\\.)*)"|'((?:[^'\\\r\n]|\\.)*)'/)))return new k.Quoted(a[0],a[1]||a[2],b)},keyword:function(){var a;if(a=e(/^[_A-Za-z-][_A-Za-z0-9-]*/))return k.colors.hasOwnProperty(a)?new k.Color(k.colors[a].slice(1)):new k.Keyword(a)},call:function(){var b,c,d=m;if(b=/^([\w-]+|%|progid:[\w\.]+)\(/.exec(v[q])){b=
b[1];c=b.toLowerCase();if("url"===c)return null;m+=b.length;if("alpha"===c&&(c=e(this.alpha),"undefined"!==typeof c))return c;e("(");c=e(this.entities.arguments);if(e(")")&&b)return new k.Call(b,c,d,a.filename,a.rootpath)}},arguments:function(){for(var a=[],b;(b=e(this.entities.assignment)||e(this.expression))&&!(a.push(b),!e(",")););return a},literal:function(){return e(this.entities.dimension)||e(this.entities.color)||e(this.entities.quoted)||e(this.entities.unicodeDescriptor)},assignment:function(){var a,
b;if((a=e(/^\w+(?=\s?=)/i))&&e("=")&&(b=e(this.entity)))return new k.Assignment(a,b)},url:function(){var b;if("u"===p.charAt(m)&&e(/^url\(/))return b=e(this.entities.quoted)||e(this.entities.variable)||e(/^(?:(?:\\[\(\)'"])|[^\(\)'"])+/)||"",l(")"),new k.URL(null!=b.value||b instanceof k.Variable?b:new k.Anonymous(b),a.rootpath)},variable:function(){var b,c=m;if("@"===p.charAt(m)&&(b=e(/^@@?[\w-]+/)))return new k.Variable(b,c,a.filename)},variableCurly:function(){var b,c=m;if("@"===p.charAt(m)&&(b=
e(/^@\{([\w-]+)\}/)))return new k.Variable("@"+b[1],c,a.filename)},color:function(){var a;if("#"===p.charAt(m)&&(a=e(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})/)))return new k.Color(a[1])},dimension:function(){var a;a=p.charCodeAt(m);if(!(57<a||43>a)&&!(47===a||44==a))if(a=e(/^([+-]?\d*\.?\d+)(%|[a-z]+)?/))return new k.Dimension(a[1],a[2])},unicodeDescriptor:function(){var a;if(a=e(/^U\+[0-9a-fA-F?]+(\-[0-9a-fA-F?]+)?/))return new k.UnicodeDescriptor(a[0])},javascript:function(){var a;a=m;var b;"~"===p.charAt(a)&&
(a++,b=!0);if("`"===p.charAt(a)&&(b&&e("~"),a=e(/^`([^`]*)`/)))return new k.JavaScript(a[1],m,b)}},variable:function(){var a;if("@"===p.charAt(m)&&(a=e(/^(@[\w-]+)\s*:/)))return a[1]},extend:function(a){var b=[],c,d=m;if(e(a?/^&:extend\(/:/^:extend\(/)){for(;c=e(/^[#.](?:[\w-]|\\(?:[a-fA-F0-9]{1,6} ?|[^a-fA-F0-9]))+/);)b.push(new k.Element(null,c,m));l(/^\)/);a&&l(/^;/);return new k.Extend(b,d)}},extendRule:function(){return this.extend(!0)},mixin:{call:function(){var d=[],f,g,j=[],n=[],q,r,H,s=m;
f=p.charAt(m);var t,A,u=!1;if(!("."!==f&&"#"!==f)){for(b();f=e(/^[#.](?:[\w-]|\\(?:[A-Fa-f0-9]{1,6} ?|[^A-Fa-f0-9]))+/);)d.push(new k.Element(g,f,m)),g=e(">");if(e("(")){for(f=[];q=e(this.expression);)if(g=null,q.throwAwayComments(),A=q,1==q.value.length&&(q=q.value[0],q instanceof k.Variable&&e(":")&&(0<f.length&&(r&&h("Cannot mix ; and , as delimiter types"),H=!0),A=l(this.expression),g=t=q.name)),f.push(A),n.push({name:g,value:A}),!e(",")&&(e(";")||r))H&&h("Cannot mix ; and , as delimiter types"),
r=!0,1<f.length&&(A=new k.Value(f)),j.push({name:t,value:A}),t=null,f=[],H=!1;l(")")}j=r?j:n;e(this.important)&&(u=!0);if(0<d.length&&(e(";")||z("}")))return new k.mixin.Call(d,j,s,a.filename,u);c()}},definition:function(){var a,d=[],f,h,g,j=!1;if(!("."!==p.charAt(m)&&"#"!==p.charAt(m)||z(/^[^{]*\}/)))if(b(),a=e(/^([#.](?:[\w-]|\\(?:[A-Fa-f0-9]{1,6} ?|[^A-Fa-f0-9]))+)\s*\(/)){a=a[1];do if(e(this.comment),"."===p.charAt(m)&&e(/^\.{3}/)){j=!0;d.push({variadic:!0});break}else if(f=e(this.entities.variable)||
e(this.entities.literal)||e(this.entities.keyword))if(f instanceof k.Variable)if(e(":"))h=l(this.expression,"expected expression"),d.push({name:f.name,value:h});else if(e(/^\.{3}/)){d.push({name:f.name,variadic:!0});j=!0;break}else d.push({name:f.name});else d.push({value:f});else break;while(e(",")||e(";"));e(")")||(x=m,c());e(this.comment);e(/^when/)&&(g=l(this.conditions,"expected condition"));if(f=e(this.block))return new k.mixin.Definition(a,d,f,g,j);c()}}},entity:function(){return e(this.entities.literal)||
e(this.entities.variable)||e(this.entities.url)||e(this.entities.call)||e(this.entities.keyword)||e(this.entities.javascript)||e(this.comment)},end:function(){return e(";")||z("}")},alpha:function(){var a;if(e(/^\(opacity=/i)&&(a=e(/^\d+/)||e(this.entities.variable)))return l(")"),new k.Alpha(a)},element:function(){var a,b,c;b=e(this.combinator);a=e(/^(?:\d+\.\d+|\d+)%/)||e(/^(?:[.#]?|:*)(?:[\w-]|[^\x00-\x9f]|\\(?:[A-Fa-f0-9]{1,6} ?|[^A-Fa-f0-9]))+/)||e("*")||e("&")||e(this.attribute)||e(/^\([^()@]+\)/)||
e(/^[\.#](?=@)/)||e(this.entities.variableCurly);if(!a&&e("(")&&(c=e(this.selector))&&e(")"))a=new k.Paren(c);if(a)return new k.Element(b,a,m)},combinator:function(){var a=p.charAt(m);if(">"===a||"+"===a||"~"===a||"|"===a){for(m++;p.charAt(m).match(/\s/);)m++;return new k.Combinator(a)}return p.charAt(m-1).match(/\s/)?new k.Combinator(" "):new k.Combinator(null)},selector:function(){for(var a,b=[],c,d;((d=e(this.extend))||(a=e(this.element)))&&a&&!(c=p.charAt(m),b.push(a),a=null,"{"===c||"}"===c||
";"===c||","===c||")"===c););if(0<b.length)return new k.Selector(b,d);d&&h("Extend must be used to extend a selector")},attribute:function(){var a="",b,c,d;if(e("[")){if(b=e(/^(?:[_A-Za-z0-9-]|\\.)+/)||e(this.entities.quoted))a=(d=e(/^[|~*$^]?=/))&&(c=e(this.entities.quoted)||e(/^[\w-]+/))?[b,d,c.toCSS?c.toCSS():c].join(""):b;if(e("]")&&a)return"["+a+"]"}},block:function(){var a;if(e("{")&&(a=e(this.primary))&&e("}"))return a},ruleset:function(){var d=[],f,h,l;b();for(a.dumpLineNumbers&&(l=s(m,p,
a));f=e(this.selector);){d.push(f);e(this.comment);if(!e(","))break;e(this.comment)}if(0<d.length&&(h=e(this.block)))return d=new k.Ruleset(d,h,a.strictImports),a.dumpLineNumbers&&(d.debugInfo=l),d;x=m;c()},rule:function(){var d,f;d=p.charAt(m);var h;b();if(!("."===d||"#"===d||"&"===d))if(d=e(this.variable)||e(this.property)){!a.compress&&"@"!=d.charAt(0)&&(f=/^([^@+\/'"*`(;{}-]*);/.exec(v[q]))?(m+=f[0].length-1,f=new k.Anonymous(f[1])):f=e(this.value);h=e(this.important);if(f&&e(this.end))return new k.Rule(d,
f,h,u);x=m;c()}},"import":function(){var d,f,h=m;b();var l=e(/^@import(?:-(once|multiple))?\s+/);if(l&&(d=e(this.entities.quoted)||e(this.entities.url)))if(f=e(this.mediaFeatures),e(";"))return new k.Import(d,w,f,"multiple"!==l[1],h,a.rootpath);c()},mediaFeature:function(){var a,b,c=[];do if(a=e(this.entities.keyword))c.push(a);else if(e("("))if(b=e(this.property),a=e(this.value),e(")"))if(b&&a)c.push(new k.Paren(new k.Rule(b,a,null,m,!0)));else if(a)c.push(new k.Paren(a));else return null;else return null;
while(a);if(0<c.length)return new k.Expression(c)},mediaFeatures:function(){var a,b=[];do if(a=e(this.mediaFeature)){if(b.push(a),!e(","))break}else if(a=e(this.entities.variable))if(b.push(a),!e(","))break;while(a);return 0<b.length?b:null},media:function(){var b,c,d;a.dumpLineNumbers&&(d=s(m,p,a));if(e(/^@media/)&&(b=e(this.mediaFeatures),c=e(this.block)))return b=new k.Media(c,b),a.dumpLineNumbers&&(b.debugInfo=d),b},directive:function(){var d,f,h,l,g;if("@"===p.charAt(m)){if(f=e(this["import"])||
e(this.media))return f;b();if(d=e(/^@[a-z-]+/)){f=d;"-"==d.charAt(1)&&0<d.indexOf("-",2)&&(f="@"+d.slice(d.indexOf("-",2)+1));switch(f){case "@font-face":h=!0;break;case "@viewport":case "@top-left":case "@top-left-corner":case "@top-center":case "@top-right":case "@top-right-corner":case "@bottom-left":case "@bottom-left-corner":case "@bottom-center":case "@bottom-right":case "@bottom-right-corner":case "@left-top":case "@left-middle":case "@left-bottom":case "@right-top":case "@right-middle":case "@right-bottom":h=
!0;break;case "@page":case "@document":case "@supports":case "@keyframes":l=h=!0;break;case "@namespace":g=!0}l&&(d+=" "+(e(/^[^{]+/)||"").trim());if(h){if(h=e(this.block))return new k.Directive(d,h)}else if((f=g?e(this.expression):e(this.entity))&&e(";"))return d=new k.Directive(d,f),a.dumpLineNumbers&&(d.debugInfo=s(m,p,a)),d;c()}}},value:function(){for(var a,b=[];(a=e(this.expression))&&!(b.push(a),!e(",")););if(0<b.length)return new k.Value(b)},important:function(){if("!"===p.charAt(m))return e(/^! *important/)},
sub:function(){var a;if(e("(")&&(a=e(this.addition)))return a=new k.Expression([a]),l(")"),a.parens=!0,a},multiplication:function(){var a,b,c,d,h;if(a=e(this.operand)){for(h=f(p.charAt(m-1));!z(/^\/[*\/]/)&&(c=e("/")||e("*"));)if(b=e(this.operand))a.parensInOp=!0,b.parensInOp=!0,d=new k.Operation(c,[d||a,b],h),h=f(p.charAt(m-1));else break;return d||a}},addition:function(){var a,b,c,d,h;if(a=e(this.multiplication)){for(h=f(p.charAt(m-1));(c=e(/^[-+]\s+/)||!h&&(e("+")||e("-")))&&(b=e(this.multiplication));)a.parensInOp=
!0,b.parensInOp=!0,d=new k.Operation(c,[d||a,b],h),h=f(p.charAt(m-1));return d||a}},conditions:function(){var a,b,c=m,d;if(a=e(this.condition)){for(;e(",")&&(b=e(this.condition));)d=new k.Condition("or",d||a,b,c);return d||a}},condition:function(){var a,b,c,d,f=m,g=!1;e(/^not/)&&(g=!0);l("(");if(a=e(this.addition)||e(this.entities.keyword)||e(this.entities.quoted))return(d=e(/^(?:>=|=<|[<=>])/))?(b=e(this.addition)||e(this.entities.keyword)||e(this.entities.quoted))?c=new k.Condition(d,a,b,f,g):h("expected expression"):
c=new k.Condition("=",a,new k.Keyword("true"),f,g),l(")"),e(/^and/)?new k.Condition("and",c,e(this.condition)):c},operand:function(){var a,b=p.charAt(m+1);if("-"===p.charAt(m)&&("@"===b||"("===b))a=e("-");b=e(this.sub)||e(this.entities.dimension)||e(this.entities.color)||e(this.entities.variable)||e(this.entities.call);a&&(b.parensInOp=!0,b=new k.Negative(b));return b},expression:function(){for(var a,b,c=[];a=e(this.addition)||e(this.entity);)c.push(a),!z(/^\/[\/*]/)&&(b=e("/"))&&c.push(new k.Anonymous(b));
if(0<c.length)return new k.Expression(c)},property:function(){var a;if(a=e(/^(\*?-?[_a-z0-9-]+)\s*:/))return a[1]}}}};if("browser"===j.mode||"rhino"===j.mode)j.Parser.importer=function(a,b,c,d){!/^([a-z-]+:)?\//.test(a)&&0<b.length&&(a=b[0]+a);ma(d.toSheet(a),function(a,b,d,h,g,j){c.call(null,a,b,j)},!0)};var g=n("./tree"),E=function(a){return g.functions.hsla(a.h,a.s,a.l,a.a)},y=function(a){if(a instanceof g.Dimension)return parseFloat(a.unit.is("%")?a.value/100:a.value);if("number"===typeof a)return a;
throw{error:"RuntimeError",message:"color functions take numbers as parameters"};},J=function(a){return Math.min(1,Math.max(0,a))};g.functions={rgb:function(a,b,c){return this.rgba(a,b,c,1)},rgba:function(a,b,c,d){a=[a,b,c].map(function(a){return a instanceof g.Dimension&&a.unit.is("%")?parseFloat(256*a.value/100):y(a)});d=y(d);return new g.Color(a,d)},hsl:function(a,b,c){return this.hsla(a,b,c,1)},hsla:function(a,b,c,d){function f(a){a=0>a?a+1:1<a?a-1:a;return 1>6*a?l+6*(e-l)*a:1>2*a?e:2>3*a?l+6*
(e-l)*(2/3-a):l}a=y(a)%360/360;b=y(b);c=y(c);d=y(d);var e=0.5>=c?c*(b+1):c+b-c*b,l=2*c-e;return this.rgba(255*f(a+1/3),255*f(a),255*f(a-1/3),d)},hsv:function(a,b,c){return this.hsva(a,b,c,1)},hsva:function(a,b,c,d){a=360*(y(a)%360/360);b=y(b);c=y(c);d=y(d);var f;f=Math.floor(a/60%6);a=a/60-f;b=[c,c*(1-b),c*(1-a*b),c*(1-(1-a)*b)];c=[[0,3,1],[2,0,1],[1,0,3],[1,2,0],[3,1,0],[0,1,2]];return this.rgba(255*b[c[f][0]],255*b[c[f][1]],255*b[c[f][2]],d)},hue:function(a){return new g.Dimension(Math.round(a.toHSL().h))},
saturation:function(a){return new g.Dimension(Math.round(100*a.toHSL().s),"%")},lightness:function(a){return new g.Dimension(Math.round(100*a.toHSL().l),"%")},hsvhue:function(a){return new g.Dimension(Math.round(a.toHSV().h))},hsvsaturation:function(a){return new g.Dimension(Math.round(100*a.toHSV().s),"%")},hsvvalue:function(a){return new g.Dimension(Math.round(100*a.toHSV().v),"%")},red:function(a){return new g.Dimension(a.rgb[0])},green:function(a){return new g.Dimension(a.rgb[1])},blue:function(a){return new g.Dimension(a.rgb[2])},
alpha:function(a){return new g.Dimension(a.toHSL().a)},luma:function(a){return new g.Dimension(Math.round(100*a.luma()*a.alpha),"%")},saturate:function(a,b){var c=a.toHSL();c.s+=b.value/100;c.s=J(c.s);return E(c)},desaturate:function(a,b){var c=a.toHSL();c.s-=b.value/100;c.s=J(c.s);return E(c)},lighten:function(a,b){var c=a.toHSL();c.l+=b.value/100;c.l=J(c.l);return E(c)},darken:function(a,b){var c=a.toHSL();c.l-=b.value/100;c.l=J(c.l);return E(c)},fadein:function(a,b){var c=a.toHSL();c.a+=b.value/
100;c.a=J(c.a);return E(c)},fadeout:function(a,b){var c=a.toHSL();c.a-=b.value/100;c.a=J(c.a);return E(c)},fade:function(a,b){var c=a.toHSL();c.a=b.value/100;c.a=J(c.a);return E(c)},spin:function(a,b){var c=a.toHSL(),d=(c.h+b.value)%360;c.h=0>d?360+d:d;return E(c)},mix:function(a,b,c){c||(c=new g.Dimension(50));c=c.value/100;var d=2*c-1,f=a.toHSL().a-b.toHSL().a,d=((-1==d*f?d:(d+f)/(1+d*f))+1)/2,f=1-d;return new g.Color([a.rgb[0]*d+b.rgb[0]*f,a.rgb[1]*d+b.rgb[1]*f,a.rgb[2]*d+b.rgb[2]*f],a.alpha*c+
b.alpha*(1-c))},greyscale:function(a){return this.desaturate(a,new g.Dimension(100))},contrast:function(a,b,c,d){if(!a.rgb)return null;"undefined"===typeof c&&(c=this.rgba(255,255,255,1));"undefined"===typeof b&&(b=this.rgba(0,0,0,1));if(b.luma()>c.luma()){var f=c;c=b;b=f}d="undefined"===typeof d?0.43:y(d);return a.luma()*a.alpha<d?c:b},e:function(a){return new g.Anonymous(a instanceof g.JavaScript?a.evaluated:a)},escape:function(a){return new g.Anonymous(encodeURI(a.value).replace(/=/g,"%3D").replace(/:/g,
"%3A").replace(/#/g,"%23").replace(/;/g,"%3B").replace(/\(/g,"%28").replace(/\)/g,"%29"))},"%":function(a){for(var b=Array.prototype.slice.call(arguments,1),c=a.value,d=0;d<b.length;d++)c=c.replace(/%[sda]/i,function(a){var c=a.match(/s/i)?b[d].value:b[d].toCSS();return a.match(/[A-Z]$/)?encodeURIComponent(c):c});c=c.replace(/%%/g,"%");return new g.Quoted('"'+c+'"',c)},unit:function(a,b){return new g.Dimension(a.value,b?b.toCSS():"")},convert:function(a,b){return a.convertTo(b.value)},round:function(a,
b){var c="undefined"===typeof b?0:b.value;return this._math(function(a){return a.toFixed(c)},null,a)},pi:function(){return new g.Dimension(Math.PI)},mod:function(a,b){return new g.Dimension(a.value%b.value,a.unit)},pow:function(a,b){if("number"===typeof a&&"number"===typeof b)a=new g.Dimension(a),b=new g.Dimension(b);else if(!(a instanceof g.Dimension)||!(b instanceof g.Dimension))throw{type:"Argument",message:"arguments must be numbers"};return new g.Dimension(Math.pow(a.value,b.value),a.unit)},
_math:function(a,b,c){if(c instanceof g.Dimension)return new g.Dimension(a(parseFloat(c.value)),null==b?c.unit:b);if("number"===typeof c)return a(c);throw{type:"Argument",message:"argument must be a number"};},argb:function(a){return new g.Anonymous(a.toARGB())},percentage:function(a){return new g.Dimension(100*a.value,"%")},color:function(a){if(a instanceof g.Quoted)return new g.Color(a.value.slice(1));throw{type:"Argument",message:"argument must be a string"};},iscolor:function(a){return this._isa(a,
g.Color)},isnumber:function(a){return this._isa(a,g.Dimension)},isstring:function(a){return this._isa(a,g.Quoted)},iskeyword:function(a){return this._isa(a,g.Keyword)},isurl:function(a){return this._isa(a,g.URL)},ispixel:function(a){return a instanceof g.Dimension&&a.unit.is("px")?g.True:g.False},ispercentage:function(a){return a instanceof g.Dimension&&a.unit.is("%")?g.True:g.False},isem:function(a){return a instanceof g.Dimension&&a.unit.is("em")?g.True:g.False},_isa:function(a,b){return a instanceof
b?g.True:g.False},multiply:function(a,b){return this.rgb(a.rgb[0]*b.rgb[0]/255,a.rgb[1]*b.rgb[1]/255,a.rgb[2]*b.rgb[2]/255)},screen:function(a,b){return this.rgb(255-(255-a.rgb[0])*(255-b.rgb[0])/255,255-(255-a.rgb[1])*(255-b.rgb[1])/255,255-(255-a.rgb[2])*(255-b.rgb[2])/255)},overlay:function(a,b){return this.rgb(128>a.rgb[0]?2*a.rgb[0]*b.rgb[0]/255:255-2*(255-a.rgb[0])*(255-b.rgb[0])/255,128>a.rgb[1]?2*a.rgb[1]*b.rgb[1]/255:255-2*(255-a.rgb[1])*(255-b.rgb[1])/255,128>a.rgb[2]?2*a.rgb[2]*b.rgb[2]/
255:255-2*(255-a.rgb[2])*(255-b.rgb[2])/255)},softlight:function(a,b){var c=b.rgb[0]*a.rgb[0]/255,d=c+a.rgb[0]*(255-(255-a.rgb[0])*(255-b.rgb[0])/255-c)/255,c=b.rgb[1]*a.rgb[1]/255,f=c+a.rgb[1]*(255-(255-a.rgb[1])*(255-b.rgb[1])/255-c)/255,c=b.rgb[2]*a.rgb[2]/255;return this.rgb(d,f,c+a.rgb[2]*(255-(255-a.rgb[2])*(255-b.rgb[2])/255-c)/255)},hardlight:function(a,b){return this.rgb(128>b.rgb[0]?2*b.rgb[0]*a.rgb[0]/255:255-2*(255-b.rgb[0])*(255-a.rgb[0])/255,128>b.rgb[1]?2*b.rgb[1]*a.rgb[1]/255:255-
2*(255-b.rgb[1])*(255-a.rgb[1])/255,128>b.rgb[2]?2*b.rgb[2]*a.rgb[2]/255:255-2*(255-b.rgb[2])*(255-a.rgb[2])/255)},difference:function(a,b){var c=Math.abs(a.rgb[0]-b.rgb[0]),d=Math.abs(a.rgb[1]-b.rgb[1]),f=Math.abs(a.rgb[2]-b.rgb[2]);return this.rgb(c,d,f)},exclusion:function(a,b){return this.rgb(a.rgb[0]+b.rgb[0]*(255-a.rgb[0]-a.rgb[0])/255,a.rgb[1]+b.rgb[1]*(255-a.rgb[1]-a.rgb[1])/255,a.rgb[2]+b.rgb[2]*(255-a.rgb[2]-a.rgb[2])/255)},average:function(a,b){return this.rgb((a.rgb[0]+b.rgb[0])/2,(a.rgb[1]+
b.rgb[1])/2,(a.rgb[2]+b.rgb[2])/2)},negation:function(a,b){var c=255-Math.abs(255-b.rgb[0]-a.rgb[0]),d=255-Math.abs(255-b.rgb[1]-a.rgb[1]),f=255-Math.abs(255-b.rgb[2]-a.rgb[2]);return this.rgb(c,d,f)},tint:function(a,b){return this.mix(this.rgb(255,255,255),a,b)},shade:function(a,b){return this.mix(this.rgb(0,0,0),a,b)},extract:function(a,b){b=b.value-1;return a.value[b]},"data-uri":function(a,b){if("undefined"!==typeof x)return(new j.tree.URL(b||a,this.rootpath)).eval(this.env);a=a.value;b=b&&b.value;
var c=n("fs"),d=!1;if(2>arguments.length){var f;try{f=n("mime")}catch(e){f=g._mime}b=a;a=f.lookup(b);d=f.charsets.lookup(a);(d=0>["US-ASCII","UTF-8"].indexOf(d))&&(a+=";base64")}else d=/;base64$/.test(a);c=c.readFileSync(b);c=d?c.toString("base64"):encodeURIComponent(c);return new g.URL(new g.Anonymous("'data:"+a+","+c+"'"))}};g._mime={_types:{".htm":"text/html",".html":"text/html",".gif":"image/gif",".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png"},lookup:function(a){a=n("path").extname(a);
var b=g._mime._types[a];if(b===ca)throw Error('Optional dependency "mime" is required for '+a);return b},charsets:{lookup:function(a){return a&&/^text\//.test(a)?"UTF-8":""}}};for(var s=[{name:"ceil"},{name:"floor"},{name:"sqrt"},{name:"abs"},{name:"tan",unit:""},{name:"sin",unit:""},{name:"cos",unit:""},{name:"atan",unit:"rad"},{name:"asin",unit:"rad"},{name:"acos",unit:"rad"}],ra=function(a,b){return function(c){null!=b&&(c=c.unify());return this._math(Math[a],b,c)}},S=0;S<s.length;S++)g.functions[s[S].name]=
ra(s[S].name,s[S].unit);g.functionCall=function(a,b){this.env=a;this.rootpath=b};g.functionCall.prototype=g.functions;n("./tree").colors={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",
cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgrey:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",
firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",grey:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",
lightgray:"#d3d3d3",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",
mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",
rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};
s=n("../tree");s.Alpha=function(a){this.value=a};s.Alpha.prototype={toCSS:function(){return"alpha(opacity="+(this.value.toCSS?this.value.toCSS():this.value)+")"},eval:function(a){this.value.eval&&(this.value=this.value.eval(a));return this}};s=n("../tree");s.Anonymous=function(a){this.value=a.value||a};s.Anonymous.prototype={toCSS:function(){return this.value},eval:function(){return this},compare:function(a){if(!a.toCSS)return-1;var b=this.toCSS();a=a.toCSS();return b===a?0:b<a?-1:1}};var fa=n("../tree");
fa.Assignment=function(a,b){this.key=a;this.value=b};fa.Assignment.prototype={toCSS:function(){return this.key+"="+(this.value.toCSS?this.value.toCSS():this.value)},eval:function(a){return this.value.eval?new fa.Assignment(this.key,this.value.eval(a)):this}};var T=n("../tree");T.Call=function(a,b,c,d,f){this.name=a;this.args=b;this.index=c;this.filename=d;this.rootpath=f};T.Call.prototype={eval:function(a){var b=this.args.map(function(b){return b.eval(a)}),c,d;if(this.name in T.functions)try{if(d=
new T.functionCall(a,this.rootpath),c=d[this.name].apply(d,b),null!=c)return c}catch(f){throw{type:f.type||"Runtime",message:"error evaluating function `"+this.name+"`"+(f.message?": "+f.message:""),index:this.index,filename:this.filename};}return new T.Anonymous(this.name+"("+b.map(function(b){return b.toCSS(a)}).join(", ")+")")},toCSS:function(a){return this.eval(a).toCSS()}};var U=n("../tree");U.Color=function(a,b){this.rgb=Array.isArray(a)?a:6==a.length?a.match(/.{2}/g).map(function(a){return parseInt(a,
16)}):a.split("").map(function(a){return parseInt(a+a,16)});this.alpha="number"===typeof b?b:1};U.Color.prototype={eval:function(){return this},luma:function(){return 0.2126*this.rgb[0]/255+0.7152*this.rgb[1]/255+0.0722*this.rgb[2]/255},toCSS:function(a,b){var c=a&&a.compress&&!b;if(1>this.alpha)return"rgba("+this.rgb.map(function(a){return Math.round(a)}).concat(this.alpha).join(","+(c?"":" "))+")";var d=this.rgb.map(function(a){a=Math.round(a);a=(255<a?255:0>a?0:a).toString(16);return 1===a.length?
"0"+a:a}).join("");c&&(d=d.split(""),d=d[0]==d[1]&&d[2]==d[3]&&d[4]==d[5]?d[0]+d[2]+d[4]:d.join(""));return"#"+d},operate:function(a,b,c){var d=[];c instanceof U.Color||(c=c.toColor());for(var f=0;3>f;f++)d[f]=U.operate(a,b,this.rgb[f],c.rgb[f]);return new U.Color(d,this.alpha+c.alpha)},toHSL:function(){var a=this.rgb[0]/255,b=this.rgb[1]/255,c=this.rgb[2]/255,d=this.alpha,f=Math.max(a,b,c),e=Math.min(a,b,c),l,h=(f+e)/2,g=f-e;if(f===e)l=e=0;else{e=0.5<h?g/(2-f-e):g/(f+e);switch(f){case a:l=(b-c)/
g+(b<c?6:0);break;case b:l=(c-a)/g+2;break;case c:l=(a-b)/g+4}l/=6}return{h:360*l,s:e,l:h,a:d}},toHSV:function(){var a=this.rgb[0]/255,b=this.rgb[1]/255,c=this.rgb[2]/255,d=this.alpha,f=Math.max(a,b,c),e=Math.min(a,b,c),l,h=f-e;if(f===e)l=0;else{switch(f){case a:l=(b-c)/h+(b<c?6:0);break;case b:l=(c-a)/h+2;break;case c:l=(a-b)/h+4}l/=6}return{h:360*l,s:0===f?0:h/f,v:f,a:d}},toARGB:function(){return"#"+[Math.round(255*this.alpha)].concat(this.rgb).map(function(a){a=Math.round(a);a=(255<a?255:0>a?0:
a).toString(16);return 1===a.length?"0"+a:a}).join("")},compare:function(a){return!a.rgb?-1:a.rgb[0]===this.rgb[0]&&a.rgb[1]===this.rgb[1]&&a.rgb[2]===this.rgb[2]&&a.alpha===this.alpha?0:-1}};s=n("../tree");s.Comment=function(a,b){this.value=a;this.silent=!!b};s.Comment.prototype={toCSS:function(a){return a.compress?"":this.value},eval:function(){return this}};s=n("../tree");s.Condition=function(a,b,c,d,f){this.op=a.trim();this.lvalue=b;this.rvalue=c;this.index=d;this.negate=f};s.Condition.prototype.eval=
function(a){var b=this.lvalue.eval(a),c=this.rvalue.eval(a),d=this.index,f;f=function(a){switch(a){case "and":return b&&c;case "or":return b||c;default:if(b.compare)f=b.compare(c);else if(c.compare)f=c.compare(b);else throw{type:"Type",message:"Unable to perform comparison",index:d};switch(f){case -1:return"<"===a||"=<"===a;case 0:return"="===a||">="===a||"=<"===a;case 1:return">"===a||">="===a}}}(this.op);return this.negate?!f:f};var r=n("../tree");r.Dimension=function(a,b){this.value=parseFloat(a);
this.unit=b&&b instanceof r.Unit?b:new r.Unit(b?[b]:ca)};r.Dimension.prototype={eval:function(){return this},toColor:function(){return new r.Color([this.value,this.value,this.value])},toCSS:function(a){if((!a||!1!==a.strictUnits)&&!this.unit.isSingular())throw Error("Multiple units in dimension. Correct the units or use the unit function. Bad unit: "+this.unit.toString());var b=this.value,c=String(b);if(a&&a.compress){if(0===b&&!this.unit.isAngle())return c;0<b&&1>b&&(c=c.substr(1))}return this.unit.isEmpty()?
c:c+this.unit.toCSS()},operate:function(a,b,c){var d=r.operate(a,b,this.value,c.value),f=this.unit.clone();if("+"===b||"-"===b)if(0===f.numerator.length&&0===f.denominator.length)f.numerator=c.unit.numerator.slice(0),f.denominator=c.unit.denominator.slice(0);else{if(!(0==c.unit.numerator.length&&0==f.denominator.length)){c=c.convertTo(this.unit.usedUnits());if(!1!==a.strictUnits&&c.unit.toString()!==f.toString())throw Error("Incompatible units. Change the units or use the unit function. Bad units: '"+
f.toString()+"' and '"+c.unit.toString()+"'.");d=r.operate(a,b,this.value,c.value)}}else"*"===b?(f.numerator=f.numerator.concat(c.unit.numerator).sort(),f.denominator=f.denominator.concat(c.unit.denominator).sort(),f.cancel()):"/"===b&&(f.numerator=f.numerator.concat(c.unit.denominator).sort(),f.denominator=f.denominator.concat(c.unit.numerator).sort(),f.cancel());return new r.Dimension(d,f)},compare:function(a){if(a instanceof r.Dimension){var b=this.unify();a=a.unify();var c=b.value,d=a.value;return d>
c?-1:d<c?1:!a.unit.isEmpty()&&0!==b.unit.compare(a)?-1:0}return-1},unify:function(){return this.convertTo({length:"m",duration:"s",angle:"rad"})},convertTo:function(a){var b=this.value,c=this.unit.clone(),d,f,e,l,h={};if("string"===typeof a){for(d in r.UnitConversions)r.UnitConversions[d].hasOwnProperty(a)&&(h={},h[d]=a);a=h}for(f in a)a.hasOwnProperty(f)&&(l=a[f],e=r.UnitConversions[f],c.map(function(a,c){return e.hasOwnProperty(a)?(b=c?b/(e[a]/e[l]):b*(e[a]/e[l]),l):a}));c.cancel();return new r.Dimension(b,
c)}};r.UnitConversions={length:{m:1,cm:0.01,mm:0.001,"in":0.0254,pt:0.0254/72,pc:12*(0.0254/72)},duration:{s:1,ms:0.001},angle:{rad:1/(2*Math.PI),deg:1/360,grad:0.0025,turn:1}};r.Unit=function(a,b){this.numerator=a?a.slice(0).sort():[];this.denominator=b?b.slice(0).sort():[]};r.Unit.prototype={clone:function(){return new r.Unit(this.numerator.slice(0),this.denominator.slice(0))},toCSS:function(){return 1<=this.numerator.length?this.numerator[0]:1<=this.denominator.length?this.denominator[0]:""},toString:function(){var a,
b=this.numerator.join("*");for(a=0;a<this.denominator.length;a++)b+="/"+this.denominator[a];return b},compare:function(a){return this.is(a.toCSS())?0:-1},is:function(a){return this.toCSS()===a},isAngle:function(){return r.UnitConversions.angle.hasOwnProperty(this.toCSS())},isEmpty:function(){return 0==this.numerator.length&&0==this.denominator.length},isSingular:function(){return 1>=this.numerator.length&&0==this.denominator.length},map:function(a){var b;for(b=0;b<this.numerator.length;b++)this.numerator[b]=
a(this.numerator[b],!1);for(b=0;b<this.denominator.length;b++)this.denominator[b]=a(this.denominator[b],!0)},usedUnits:function(){var a,b,c={};for(b in r.UnitConversions)r.UnitConversions.hasOwnProperty(b)&&(a=r.UnitConversions[b],this.map(function(d){a.hasOwnProperty(d)&&!c[b]&&(c[b]=d);return d}));return c},cancel:function(){var a={},b,c;for(c=0;c<this.numerator.length;c++)b=this.numerator[c],a[b]=(a[b]||0)+1;for(c=0;c<this.denominator.length;c++)b=this.denominator[c],a[b]=(a[b]||0)-1;this.numerator=
[];this.denominator=[];for(b in a)if(a.hasOwnProperty(b)){var d=a[b];if(0<d)for(c=0;c<d;c++)this.numerator.push(b);else if(0>d)for(c=0;c<-d;c++)this.denominator.push(b)}this.numerator.sort();this.denominator.sort()}};var K=n("../tree");K.Directive=function(a,b){this.name=a;Array.isArray(b)?(this.ruleset=new K.Ruleset([],b),this.ruleset.allowImports=!0):this.value=b};K.Directive.prototype={toCSS:function(a,b){return this.ruleset?(this.ruleset.root=!0,this.name+(b.compress?"{":" {\n  ")+this.ruleset.toCSS(a,
b).trim().replace(/\n/g,"\n  ")+(b.compress?"}":"\n}\n")):this.name+" "+this.value.toCSS()+";\n"},eval:function(a){var b=this;this.ruleset&&(a.frames.unshift(this),b=new K.Directive(this.name),b.ruleset=this.ruleset.eval(a),a.frames.shift());return b},variable:function(a){return K.Ruleset.prototype.variable.call(this.ruleset,a)},find:function(){return K.Ruleset.prototype.find.apply(this.ruleset,arguments)},rulesets:function(){return K.Ruleset.prototype.rulesets.apply(this.ruleset)}};var F=n("../tree");
F.Element=function(a,b,c){this.combinator=a instanceof F.Combinator?a:new F.Combinator(a);this.value="string"===typeof b?b.trim():b?b:"";this.index=c};F.Element.prototype.eval=function(a){return new F.Element(this.combinator,this.value.eval?this.value.eval(a):this.value,this.index)};F.Element.prototype.toCSS=function(a){var b=this.value.toCSS?this.value.toCSS(a):this.value;return""==b&&"&"==this.combinator.value.charAt(0)?"":this.combinator.toCSS(a||{})+b};F.Combinator=function(a){this.value=" "===
a?" ":a?a.trim():""};F.Combinator.prototype.toCSS=function(a){return{"":""," ":" ",":":" :","+":a.compress?"+":" + ","~":a.compress?"~":" ~ ",">":a.compress?">":" > ","|":a.compress?"|":" | "}[this.value]};var V=n("../tree");V.Expression=function(a){this.value=a};V.Expression.prototype={eval:function(a){var b,c=this.parens&&!this.parensInOp,d=!1;c&&a.inParenthesis();1<this.value.length?b=new V.Expression(this.value.map(function(b){return b.eval(a)})):1===this.value.length?(this.value[0].parens&&!this.value[0].parensInOp&&
(d=!0),b=this.value[0].eval(a)):b=this;c&&a.outOfParenthesis();this.parens&&(this.parensInOp&&!a.isMathsOn()&&!d)&&(b=new V.Paren(b));return b},toCSS:function(a){return this.value.map(function(b){return b.toCSS?b.toCSS(a):""}).join(" ")},throwAwayComments:function(){this.value=this.value.filter(function(a){return!(a instanceof V.Comment)})}};var W=n("../tree");W.Extend=function(a,b){this.selector=new W.Selector(a);this.index=b};W.Extend.prototype.eval=function(a,b){var c=b||a.selectors,d=[];(function l(a,
b){c[b]&&c[b].length?c[b].forEach(function(c){l(c.elements.concat(a),b+1)}):d.push({elements:a})})([],0);var f=this.selector.elements[0].value;a.frames.forEach(function(a){a.rulesets().forEach(function(a){a.selectors.forEach(function(b){b.elements.forEach(function(c,l){c.value===f&&d.forEach(function(d){d.elements[0]=new W.Element(c.combinator,d.elements[0].value,d.elements[0].index);a.selectors.push(new W.Selector(b.elements.slice(0,l).concat(d.elements).concat(b.elements.slice(l+1))))})})})})});
return this};var L=n("../tree");L.Import=function(a,b,c,d,f,e){var l=this;this.once=d;this.index=f;this._path=a;this.features=c&&new L.Value(c);this.rootpath=e;this.path=a instanceof L.Quoted?/(\.[a-z]*$)|([\?;].*)$/.test(a.value)?a.value:a.value+".less":a.value.value||a.value;(this.css=/css([\?;].*)?$/.test(this.path))||b.push(this.path,function(a,b,c){a&&(a.index=f);c&&l.once&&(l.skip=c);l.root=b||new L.Ruleset([],[])})};L.Import.prototype={toCSS:function(a){a=this.features?" "+this.features.toCSS(a):
"";return this.css?("string"===typeof this._path.value&&!/^(?:[a-z-]+:|\/)/.test(this._path.value)&&(this._path.value=this.rootpath+this._path.value),"@import "+this._path.toCSS()+a+";\n"):""},eval:function(a){var b;this.features&&this.features.eval(a);if(this.skip)return[];if(this.css)return this;b=new L.Ruleset([],this.root.rules.slice(0));b.evalImports(a);return this.features?new L.Media(b.rules,this.features.value):b.rules}};var M=n("../tree");M.JavaScript=function(a,b,c){this.escaped=c;this.expression=
a;this.index=b};M.JavaScript.prototype={eval:function(a){var b,c=this,d={},f=this.expression.replace(/@\{([\w-]+)\}/g,function(b,d){return M.jsify((new M.Variable("@"+d,c.index)).eval(a))});try{f=new Function("return ("+f+")")}catch(e){throw{message:"JavaScript evaluation error: `"+f+"`",index:this.index};}for(var l in a.frames[0].variables())d[l.slice(1)]={value:a.frames[0].variables()[l].value,toJS:function(){return this.value.eval(a).toCSS()}};try{b=f.call(d)}catch(h){throw{message:"JavaScript evaluation error: '"+
h.name+": "+h.message+"'",index:this.index};}return"string"===typeof b?new M.Quoted('"'+b+'"',b,this.escaped,this.index):Array.isArray(b)?new M.Anonymous(b.join(", ")):new M.Anonymous(b)}};var N=n("../tree");N.Keyword=function(a){this.value=a};N.Keyword.prototype={eval:function(){return this},toCSS:function(){return this.value},compare:function(a){return a instanceof N.Keyword?a.value===this.value?0:1:-1}};N.True=new N.Keyword("true");N.False=new N.Keyword("false");var u=n("../tree");u.Media=function(a,
b){var c=this.emptySelectors();this.features=new u.Value(b);this.ruleset=new u.Ruleset(c,a);this.ruleset.allowImports=!0};u.Media.prototype={toCSS:function(a,b){var c=this.features.toCSS(b);this.ruleset.root=0===a.length||a[0].multiMedia;return"@media "+c+(b.compress?"{":" {\n  ")+this.ruleset.toCSS(a,b).trim().replace(/\n/g,"\n  ")+(b.compress?"}":"\n}\n")},eval:function(a){a.mediaBlocks||(a.mediaBlocks=[],a.mediaPath=[]);var b=new u.Media([],[]);this.debugInfo&&(this.ruleset.debugInfo=this.debugInfo,
b.debugInfo=this.debugInfo);var c=!1;!1===a.strictMaths&&(c=!0,a.strictMaths=!0);try{b.features=this.features.eval(a)}finally{c&&(a.strictMaths=!1)}a.mediaPath.push(b);a.mediaBlocks.push(b);a.frames.unshift(this.ruleset);b.ruleset=this.ruleset.eval(a);a.frames.shift();a.mediaPath.pop();return 0===a.mediaPath.length?b.evalTop(a):b.evalNested(a)},variable:function(a){return u.Ruleset.prototype.variable.call(this.ruleset,a)},find:function(){return u.Ruleset.prototype.find.apply(this.ruleset,arguments)},
rulesets:function(){return u.Ruleset.prototype.rulesets.apply(this.ruleset)},emptySelectors:function(){var a=new u.Element("","&",0);return[new u.Selector([a])]},evalTop:function(a){var b=this;1<a.mediaBlocks.length&&(b=this.emptySelectors(),b=new u.Ruleset(b,a.mediaBlocks),b.multiMedia=!0);delete a.mediaBlocks;delete a.mediaPath;return b},evalNested:function(a){var b,c=a.mediaPath.concat([this]);for(b=0;b<c.length;b++)a=c[b].features instanceof u.Value?c[b].features.value:c[b].features,c[b]=Array.isArray(a)?
a:[a];this.features=new u.Value(this.permute(c).map(function(a){a=a.map(function(a){return a.toCSS?a:new u.Anonymous(a)});for(b=a.length-1;0<b;b--)a.splice(b,0,new u.Anonymous("and"));return new u.Expression(a)}));return new u.Ruleset([],[])},permute:function(a){if(0===a.length)return[];if(1===a.length)return a[0];for(var b=[],c=this.permute(a.slice(1)),d=0;d<c.length;d++)for(var f=0;f<a[0].length;f++)b.push([a[0][f]].concat(c[d]));return b},bubbleSelectors:function(a){this.ruleset=new u.Ruleset(a.slice(0),
[this.ruleset])}};var q=n("../tree");q.mixin={};q.mixin.Call=function(a,b,c,d,f){this.selector=new q.Selector(a);this.arguments=b;this.index=c;this.filename=d;this.important=f};q.mixin.Call.prototype={eval:function(a){var b,c,d,f=[],e=!1,l,h,g,j,k;d=this.arguments&&this.arguments.map(function(b){return{name:b.name,value:b.value.eval(a)}});for(l=0;l<a.frames.length;l++)if(0<(b=a.frames[l].find(this.selector)).length){k=!0;for(h=0;h<b.length;h++){c=b[h];j=!1;for(g=0;g<a.frames.length;g++)if(!(c instanceof
q.mixin.Definition)&&c===(a.frames[g].originalRuleset||a.frames[g])){j=!0;break}if(!j&&c.matchArgs(d,a)){if(!c.matchCondition||c.matchCondition(d,a))try{Array.prototype.push.apply(f,c.eval(a,d,this.important).rules)}catch(n){throw{message:n.message,index:this.index,filename:this.filename,stack:n.stack};}e=!0}}if(e)return f}if(k)throw{type:"Runtime",message:"No matching definition was found for `"+this.selector.toCSS().trim()+"("+(d?d.map(function(a){var b="";a.name&&(b+=a.name+":");return b=a.value.toCSS?
b+a.value.toCSS():b+"???"}).join(", "):"")+")`",index:this.index,filename:this.filename};throw{type:"Name",message:this.selector.toCSS().trim()+" is undefined",index:this.index,filename:this.filename};}};q.mixin.Definition=function(a,b,c,d,f){this.name=a;this.selectors=[new q.Selector([new q.Element(null,a)])];this.params=b;this.condition=d;this.variadic=f;this.arity=b.length;this.rules=c;this._lookups={};this.required=b.reduce(function(a,b){return!b.name||b.name&&!b.value?a+1:a},0);this.parent=q.Ruleset.prototype;
this.frames=[]};q.mixin.Definition.prototype={toCSS:function(){return""},variable:function(a){return this.parent.variable.call(this,a)},variables:function(){return this.parent.variables.call(this)},find:function(){return this.parent.find.apply(this,arguments)},rulesets:function(){return this.parent.rulesets.apply(this)},evalParams:function(a,b,c,d){var f=new q.Ruleset(null,[]),e,l=this.params.slice(0),h,g,j,k;if(c){c=c.slice(0);for(h=0;h<c.length;h++)if(j=(e=c[h])&&e.name){k=!1;for(g=0;g<l.length;g++)if(!d[g]&&
j===l[g].name){d[g]=e.value.eval(a);f.rules.unshift(new q.Rule(j,e.value.eval(a)));k=!0;break}if(k)c.splice(h,1),h--;else throw{type:"Runtime",message:"Named argument for "+this.name+" "+c[h].name+" not found"};}}for(h=k=0;h<l.length;h++)if(!d[h]){e=c&&c[k];if(j=l[h].name)if(l[h].variadic&&c){e=[];for(g=k;g<c.length;g++)e.push(c[g].value.eval(a));f.rules.unshift(new q.Rule(j,(new q.Expression(e)).eval(a)))}else{if(g=e&&e.value)g=g.eval(a);else if(l[h].value)g=l[h].value.eval(b);else throw{type:"Runtime",
message:"wrong number of arguments for "+this.name+" ("+c.length+" for "+this.arity+")"};f.rules.unshift(new q.Rule(j,g));d[h]=g}if(l[h].variadic&&c)for(g=k;g<c.length;g++)d[g]=c[g].value.eval(a);k++}return f},eval:function(a,b,c){var d=[],f=this.frames.concat(a.frames);b=this.evalParams(a,new q.evalEnv(a,f),b,d);b.rules.unshift(new q.Rule("@arguments",(new q.Expression(d)).eval(a)));c=c?this.parent.makeImportant.apply(this).rules:this.rules.slice(0);a=(new q.Ruleset(null,c)).eval(new q.evalEnv(a,
[this,b].concat(f)));a.originalRuleset=this;return a},matchCondition:function(a,b){return this.condition&&!this.condition.eval(new q.evalEnv(b,[this.evalParams(b,new q.evalEnv(b,this.frames.concat(b.frames)),a,[])].concat(b.frames)))?!1:!0},matchArgs:function(a,b){var c=a&&a.length||0;if(!this.variadic&&(c<this.required||c>this.params.length||0<this.required&&c>this.params.length))return!1;for(var c=Math.min(c,this.arity),d=0;d<c;d++)if(!this.params[d].name&&!this.params[d].variadic&&a[d].value.eval(b).toCSS()!=
this.params[d].value.eval(b).toCSS())return!1;return!0}};var X=n("../tree");X.Negative=function(a){this.value=a};X.Negative.prototype={toCSS:function(a){return"-"+this.value.toCSS(a)},eval:function(a){return a.isMathsOn()?(new X.Operation("*",[new X.Dimension(-1),this.value])).eval(a):new X.Negative(this.value.eval(a))}};var O=n("../tree");O.Operation=function(a,b,c){this.op=a.trim();this.operands=b;this.isSpaced=c};O.Operation.prototype.eval=function(a){var b=this.operands[0].eval(a),c=this.operands[1].eval(a),
d;if(a.isMathsOn()){if(b instanceof O.Dimension&&c instanceof O.Color)if("*"===this.op||"+"===this.op)d=c,c=b,b=d;else throw{type:"Operation",message:"Can't substract or divide a color from a number"};if(!b.operate)throw{type:"Operation",message:"Operation on an invalid type"};return b.operate(a,this.op,c)}return new O.Operation(this.op,[b,c],this.isSpaced)};O.Operation.prototype.toCSS=function(){var a=this.isSpaced?" ":"";return this.operands[0].toCSS()+a+this.op+a+this.operands[1].toCSS()};O.operate=
function(a,b,c,d){switch(b){case "+":return c+d;case "-":return c-d;case "*":return c*d;case "/":return c/d}};var ga=n("../tree");ga.Paren=function(a){this.value=a};ga.Paren.prototype={toCSS:function(a){return"("+this.value.toCSS(a).trim()+")"},eval:function(a){return new ga.Paren(this.value.eval(a))}};var Q=n("../tree");Q.Quoted=function(a,b,c,d){this.escaped=c;this.value=b||"";this.quote=a.charAt(0);this.index=d};Q.Quoted.prototype={toCSS:function(){return this.escaped?this.value:this.quote+this.value+
this.quote},eval:function(a){var b=this,c=this.value.replace(/`([^`]+)`/g,function(c,f){return(new Q.JavaScript(f,b.index,!0)).eval(a).value}).replace(/@\{([\w-]+)\}/g,function(c,f){var e=(new Q.Variable("@"+f,b.index)).eval(a,!0);return e instanceof Q.Quoted?e.value:e.toCSS()});return new Q.Quoted(this.quote+c+this.quote,c,this.escaped,this.index)},compare:function(a){if(!a.toCSS)return-1;var b=this.toCSS();a=a.toCSS();return b===a?0:b<a?-1:1}};var G=n("../tree");G.Rule=function(a,b,c,d,f){this.name=
a;this.value=b instanceof G.Value?b:new G.Value([b]);this.important=c?" "+c.trim():"";this.index=d;this.inline=f||!1;this.variable="@"===a.charAt(0)?!0:!1};G.Rule.prototype.toCSS=function(a){return this.variable?"":this.name+(a.compress?":":": ")+this.value.toCSS(a)+this.important+(this.inline?"":";")};G.Rule.prototype.eval=function(a){var b=!1;"font"===this.name&&!1===a.strictMaths&&(b=!0,a.strictMaths=!0);try{return new G.Rule(this.name,this.value.eval(a),this.important,this.index,this.inline)}finally{b&&
(a.strictMaths=!1)}};G.Rule.prototype.makeImportant=function(){return new G.Rule(this.name,this.value,"!important",this.index,this.inline)};var t=n("../tree");t.Ruleset=function(a,b,c){this.selectors=a;this.rules=b;this._lookups={};this.strictImports=c};t.Ruleset.prototype={eval:function(a){var b=this.selectors&&this.selectors.map(function(b){return b.eval(a)}),c=new t.Ruleset(b,this.rules.slice(0),this.strictImports),d;c.originalRuleset=this;c.root=this.root;c.allowImports=this.allowImports;this.debugInfo&&
(c.debugInfo=this.debugInfo);a.frames.unshift(c);a.selectors||(a.selectors=[]);a.selectors.unshift(this.selectors);(c.root||c.allowImports||!c.strictImports)&&c.evalImports(a);for(var f=0;f<c.rules.length;f++)c.rules[f]instanceof t.mixin.Definition&&(c.rules[f].frames=a.frames.slice(0));for(var e=a.mediaBlocks&&a.mediaBlocks.length||0,f=0;f<c.rules.length;f++)c.rules[f]instanceof t.mixin.Call&&(d=c.rules[f].eval(a),c.rules.splice.apply(c.rules,[f,1].concat(d)),f+=d.length-1,c.resetCache());if(this.selectors)for(f=
0;f<this.selectors.length;f++)this.selectors[f].extend&&this.selectors[f].extend.eval(a,[[this.selectors[f]]].concat(a.selectors.slice(1)));for(f=0;f<c.rules.length;f++)d=c.rules[f],d instanceof t.mixin.Definition||(c.rules[f]=d.eval?d.eval(a):d);a.frames.shift();a.selectors.shift();if(a.mediaBlocks)for(f=e;f<a.mediaBlocks.length;f++)a.mediaBlocks[f].bubbleSelectors(b);return c},evalImports:function(a){var b,c;for(b=0;b<this.rules.length;b++)this.rules[b]instanceof t.Import&&(c=this.rules[b].eval(a),
"number"===typeof c.length?(this.rules.splice.apply(this.rules,[b,1].concat(c)),b+=c.length-1):this.rules.splice(b,1,c),this.resetCache())},makeImportant:function(){return new t.Ruleset(this.selectors,this.rules.map(function(a){return a.makeImportant?a.makeImportant():a}),this.strictImports)},matchArgs:function(a){return!a||0===a.length},resetCache:function(){this._variables=this._rulesets=null;this._lookups={}},variables:function(){return this._variables?this._variables:this._variables=this.rules.reduce(function(a,
b){b instanceof t.Rule&&!0===b.variable&&(a[b.name]=b);return a},{})},variable:function(a){return this.variables()[a]},rulesets:function(){return this.rules.filter(function(a){return a instanceof t.Ruleset||a instanceof t.mixin.Definition})},find:function(a,b){b=b||this;var c=[],d=a.toCSS();if(d in this._lookups)return this._lookups[d];this.rulesets().forEach(function(d){if(d!==b)for(var e=0;e<d.selectors.length;e++)if(a.match(d.selectors[e])){a.elements.length>d.selectors[e].elements.length?Array.prototype.push.apply(c,
d.find(new t.Selector(a.elements.slice(1)),b)):c.push(d);break}});return this._lookups[d]=c},toCSS:function(a,b){var c=[],d=[],f=[],e=[],g=[],h;this.root||this.joinSelectors(g,a,this.selectors);for(var j=0;j<this.rules.length;j++)if(h=this.rules[j],h.rules||h instanceof t.Media)e.push(h.toCSS(g,b));else if(h instanceof t.Directive){var k=h.toCSS(g,b);if("@charset"===h.name){if(b.charset){h.debugInfo&&(e.push(t.debugInfo(b,h)),e.push((new t.Comment("/* "+k.replace(/\n/g,"")+" */\n")).toCSS(b)));continue}b.charset=
!0}e.push(k)}else h instanceof t.Comment?h.silent||(this.root?e.push(h.toCSS(b)):d.push(h.toCSS(b))):h.toCSS&&!h.variable?d.push(h.toCSS(b)):h.value&&!h.variable&&d.push(h.value.toString());b.compress&&d.length&&(h=d[d.length-1],";"===h.charAt(h.length-1)&&(d[d.length-1]=h.substring(0,h.length-1)));e=e.join("");if(this.root)c.push(d.join(b.compress?"":"\n"));else if(0<d.length){h=t.debugInfo(b,this);g=g.map(function(a){return a.map(function(a){return a.toCSS(b)}).join("").trim()}).join(b.compress?
",":",\n");for(j=d.length-1;0<=j;j--)-1===f.indexOf(d[j])&&f.unshift(d[j]);c.push(h+g+(b.compress?"{":" {\n  ")+f.join(b.compress?"":"\n  ")+(b.compress?"}":"\n}\n"))}c.push(e);return c.join("")+(b.compress?"\n":"")},joinSelectors:function(a,b,c){for(var d=0;d<c.length;d++)this.joinSelector(a,b,c[d])},joinSelector:function(a,b,c){var d,f,e,g,h,j,k,n,q,p,m,r;for(d=0;d<c.elements.length;d++)h=c.elements[d],"&"===h.value&&(g=!0);if(g){f=[];g=[[]];for(d=0;d<c.elements.length;d++)if(h=c.elements[d],"&"!==
h.value)f.push(h);else{r=[];0<f.length&&this.mergeElementsOnToSelectors(f,g);for(f=0;f<g.length;f++)if(j=g[f],0==b.length)0<j.length&&(j[0].elements=j[0].elements.slice(0),j[0].elements.push(new t.Element(h.combinator,"",0))),r.push(j);else for(e=0;e<b.length;e++)k=b[e],n=[],q=[],m=!0,0<j.length?(n=j.slice(0),p=n.pop(),p=new t.Selector(p.elements.slice(0)),m=!1):p=new t.Selector([]),1<k.length&&(q=q.concat(k.slice(1))),0<k.length&&(m=!1,p.elements.push(new t.Element(h.combinator,k[0].elements[0].value,
0)),p.elements=p.elements.concat(k[0].elements.slice(1))),m||n.push(p),n=n.concat(q),r.push(n);g=r;f=[]}0<f.length&&this.mergeElementsOnToSelectors(f,g);for(d=0;d<g.length;d++)0<g[d].length&&a.push(g[d])}else if(0<b.length)for(d=0;d<b.length;d++)a.push(b[d].concat(c));else a.push([c])},mergeElementsOnToSelectors:function(a,b){var c,d;if(0==b.length)b.push([new t.Selector(a)]);else for(c=0;c<b.length;c++)d=b[c],0<d.length?d[d.length-1]=new t.Selector(d[d.length-1].elements.concat(a)):d.push(new t.Selector(a))}};
var Y=n("../tree");Y.Selector=function(a,b){this.elements=a;this.extend=b};Y.Selector.prototype.match=function(a){var b=this.elements,c=b.length,d,f;a=a.elements.slice(a.elements.length&&"&"===a.elements[0].value?1:0);d=a.length;f=Math.min(c,d);if(0===d||c<d)return!1;for(c=0;c<f;c++)if(b[c].value!==a[c].value)return!1;return!0};Y.Selector.prototype.eval=function(a){return new Y.Selector(this.elements.map(function(b){return b.eval(a)}),this.extend)};Y.Selector.prototype.toCSS=function(a){if(this._css)return this._css;
this._css=""===this.elements[0].combinator.value?" ":"";return this._css+=this.elements.map(function(b){return"string"===typeof b?" "+b.trim():b.toCSS(a)}).join("")};s=n("../tree");s.UnicodeDescriptor=function(a){this.value=a};s.UnicodeDescriptor.prototype={toCSS:function(){return this.value},eval:function(){return this}};var ha=n("../tree");ha.URL=function(a,b){this.value=a;this.rootpath=b};ha.URL.prototype={toCSS:function(){return"url("+this.value.toCSS()+")"},eval:function(a){a=this.value.eval(a);
var b;this.rootpath&&("string"===typeof a.value&&!/^(?:[a-z-]+:|\/)/.test(a.value))&&(b=this.rootpath,a.quote||(b=b.replace(/[\(\)'"\s]/g,function(a){return"\\"+a})),a.value=b+a.value);return new ha.URL(a,null)}};var ia=n("../tree");ia.Value=function(a){this.value=a;this.is="value"};ia.Value.prototype={eval:function(a){return 1===this.value.length?this.value[0].eval(a):new ia.Value(this.value.map(function(b){return b.eval(a)}))},toCSS:function(a){return this.value.map(function(b){return b.toCSS(a)}).join(a.compress?
",":", ")}};var ba=n("../tree");ba.Variable=function(a,b,c){this.name=a;this.index=b;this.file=c};ba.Variable.prototype={eval:function(a){var b,c,d=this.name;0==d.indexOf("@@")&&(d="@"+(new ba.Variable(d.slice(1))).eval(a).value);if(this.evaluating)throw{type:"Name",message:"Recursive variable definition for "+d,filename:this.file,index:this.index};this.evaluating=!0;if(b=ba.find(a.frames,function(b){if(c=b.variable(d))return c.value.eval(a)}))return this.evaluating=!1,b;throw{type:"Name",message:"variable "+
d+" is undefined",filename:this.file,index:this.index};}};var D=n("./tree");D.debugInfo=function(a,b){var c="";if(a.dumpLineNumbers&&!a.compress)switch(a.dumpLineNumbers){case "comments":c=D.debugInfo.asComment(b);break;case "mediaquery":c=D.debugInfo.asMediaQuery(b);break;case "all":c=D.debugInfo.asComment(b)+D.debugInfo.asMediaQuery(b)}return c};D.debugInfo.asComment=function(a){return"/* line "+a.debugInfo.lineNumber+", "+a.debugInfo.fileName+" */\n"};D.debugInfo.asMediaQuery=function(a){return"@media -sass-debug-info{filename{font-family:"+
("file://"+a.debugInfo.fileName).replace(/[\/:.]/g,"\\$&")+"}line{font-family:\\00003"+a.debugInfo.lineNumber+"}}\n"};D.find=function(a,b){for(var c=0,d;c<a.length;c++)if(d=b.call(a,a[c]))return d;return null};D.jsify=function(a){return Array.isArray(a.value)&&1<a.value.length?"["+a.value.map(function(a){return a.toCSS(!1)}).join(", ")+"]":a.toCSS(!1)};var P=n("./tree"),sa="paths optimization filename files contents rootpath relativeUrls strictImports dumpLineNumbers compress mime entryPath rootFilename".split(" ");
P.parseEnv=function(a){na(a,this,sa);this.contents||(this.contents={});this.rootpath||(this.rootpath="");this.files||(this.files={})};P.parseEnv.prototype.toSheet=function(a){var b=new P.parseEnv(this);b.href=a;b.type=this.mime;return b};var ta=["compress","strictMaths","strictUnits"];P.evalEnv=function(a,b){na(a,this,ta);this.frames=b||[]};P.evalEnv.prototype.inParenthesis=function(){this.parensStack||(this.parensStack=[]);this.parensStack.push(!0)};P.evalEnv.prototype.outOfParenthesis=function(){this.parensStack.pop()};
P.evalEnv.prototype.isMathsOn=function(){return!1===this.strictMaths?!0:this.parensStack&&this.parensStack.length};var na=function(a,b,c){if(a)for(var d=0;d<c.length;d++)a.hasOwnProperty(c[d])&&(b[c[d]]=a[c[d]])},aa=/^(file|chrome(-extension)?|resource|qrc|app):/.test(location.protocol);j.env=j.env||("127.0.0.1"==location.hostname||"0.0.0.0"==location.hostname||"localhost"==location.hostname||0<location.port.length||aa?"development":"production");j.async=j.async||!1;j.fileAsync=j.fileAsync||!1;j.poll=
j.poll||(aa?1E3:1500);if(j.functions)for(var C in j.functions)j.tree.functions[C]=j.functions[C];if(C=/!dumpLineNumbers:(comments|mediaquery|all)/.exec(location.hash))j.dumpLineNumbers=C[1];j.watch=function(){j.watchMode||(j.env="development","development"===j.env?(j.optimization=0,j.watchTimer=setInterval(function(){j.watchMode&&la(function(a,b,c,d,f){a?Z(a,d.href):b&&R(b.toCSS(j),d,f.lastModified)})},j.poll)):j.optimization=3);return this.watchMode=!0};j.unwatch=function(){clearInterval(j.watchTimer);
return this.watchMode=!1};/!watch/.test(location.hash)&&j.watch();var w=null;if("development"!=j.env)try{w="undefined"===typeof x.localStorage?null:x.localStorage}catch(ua){}C=document.getElementsByTagName("link");var ka=/^text\/(x-)?less$/;j.sheets=[];for(s=0;s<C.length;s++)("stylesheet/less"===C[s].rel||C[s].rel.match(/stylesheet/)&&C[s].type.match(ka))&&j.sheets.push(C[s]);var da="";j.modifyVars=function(a){var b=da;for(name in a)b+=("@"===name.slice(0,1)?"":"@")+name+": "+(";"===a[name].slice(-1)?
a[name]:a[name]+";");(new j.Parser(new j.tree.parseEnv(j))).parse(b,function(a,b){a?Z(a,"session_cache"):R(b.toCSS(j),j.sheets[j.sheets.length-1])})};j.refresh=function(a){var b,c;b=c=new Date;la(function(a,f,e,g,h){if(a)return Z(a,g.href);h.local?I("loading "+g.href+" from cache."):(I("parsed "+g.href+" successfully."),R(f.toCSS(j),g,h.lastModified));I("css for "+g.href+" generated in "+(new Date-c)+"ms");0===h.remaining&&I("css generated in "+(new Date-b)+"ms");c=new Date},a);ja()};j.refreshStyles=
ja;j.refresh("development"===j.env);"function"===typeof define&&define.amd&&define(function(){return j})})(window);